# Generated by Django 4.1.1 on 2022-09-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='type',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='value',
        ),
        migrations.AlterField(
            model_name='courses',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='branches',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.courses'),
        ),
    ]
