# Generated by Django 4.1.1 on 2022-09-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_contacts_contacts_contacts_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='branches',
        ),
        migrations.AddField(
            model_name='branches',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
